---
title: "Imputation Quality Report"
output:
  rmdformats::robobook:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
params:
  input: ""
  name: ""
  population: ""
  version: ""
  date: ""
  service: ""
---

```{r setup, echo=FALSE, include=FALSE}

library(ggplot2)
library(dplyr)
```

## Parameters

| Parameter        | Value                       |
|------------------|-----------------------------|
| Job             | `r params$name`            |
| Pipeline Version | `r params$version`          |
| Date             | `r params$date`             |

## RSQ Plot
```{r echo=FALSE}
dataset = read.csv(params$input, row.names=NULL, sep = '\t')
dataset_weighted = dataset %>%
    group_by ( 
        X.Bin.Aggregated.by.MAF 
    ) %>%
    summarise ( 
        mean_MAF = mean(Average.MAF),
        variants_sum = sum(X.Variants), 
        weighted_R2 = weighted.mean(Imputation.R2,X.Variants)
    )

ggplot() + geom_line(data = dataset_weighted, mapping = aes(x = mean_MAF, y= weighted_R2))  +  scale_x_log10() +  expand_limits(x = 0, y = 0) 

```

<small>
This report has been created with **`r params$service`**.
</small>
